## NUMPY

## 1. Import numpy as np and see the version

In [3]:
pip install numpy

  Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np
print(np.__version__)

1.26.4


## 2. How to create a 1D array?


In [9]:
arr = [1,2,3,4]
arr = np.array(arr)
arr

array([1, 2, 3, 4])

## 3. How to create a boolean array?

In [13]:
np.full((3,3),fill_value = True,dtype =bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. How to extract items that satisfy a given condition from 1D array?

In [14]:
#Q. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[arr%2 !=0]

array([1, 3, 5, 7, 9])

## 5. How to replace items that satisfy a condition with another value in numpy array?

In [16]:
#Q. Replace all odd numbers in arr with -1
#Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[arr%2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. How to replace items that satisfy a condition without affecting the original array?

In [18]:
#Q. Replace all odd numbers in arr with -1 without changing arr

#Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
out = np.where(arr%2!=0,-1,arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])